############ MID Config #############
# Optimizer
lr: 0.0001
pretrain_transformer: False
pretrain_epochs: 450

# Dataset
data_dir: processed_data_noise # The path with the directory with XXX.pkl

# Training Parameters
diffnet: TransformerConcatLinear # Type of diffnet
encoder_dim: 256 # Encoder dimension
tf_layer: 3 # Number of layers of the transformer
epochs: 150
batch_size: 256
eval_batch_size: 256
k_eval: 25
seed: 123
eval_every: 15

# Testing
eval_at: 1
eval_mode: False

# Visualization
save_losses_plots: False # Used for visualization purposes only (very slow since it computes also the fake MSE loss)
use_wandb: False

# SDD longterm prediction
sdd_longterm: False

# Cosine schedule. Choose from: two_fifth_pi_cos_squared, piecewise_cos_inv, clipped_two_fifth, sigmoid, sigmoid_2
variance_sched: cosine
cosine_sched: sigmoid

# Loss function. This can be simple (MSE), hybrid (L_simple+lambda*L_vlb) or vlb (L_vlb)
loss_type: simple
ensemble_loss: False # this should work only when vlb is selected to be the loss type
ensemble_hybrid_steps: 10

# Learn variances
learn_sigmas: False
learned_range: True
lambda_vlb: 0.001

# Reduce gradient noise
reduce_grad_noise: False

# Goal module
use_goal: True
g_image_channels: 6
g_obs_len: 8
g_pred_len: 12
g_sampler_temperature: 1
g_use_ttst: True
g_loss_lambda: 0.1
g_weight_samples: 1

############### Trajectron++ Config #################
# Misc
conf: None
debug: False
preprocess_workers: 0

# Model parameters
offline_scene_graph: yes
dynamic_edges: yes
edge_state_combine_method: sum
edge_influence_combine_method: attention
edge_addition_filter: [0.25, 0.5, 0.75, 1.0]
edge_removal_filter: [1.0, 0.0]
override_attention_radius: []
incl_robot_node: False
map_encoding: False
augment: True
node_freq_mult_train: False
node_freq_mult_eval: False
scene_freq_mult_train: False
scene_freq_mult_eval: False
scene_freq_mult_viz: False
no_edge_encoding: False

# Data Parameters
device: cuda
eval_device: cuda
